= Introducció i context
:experimental:
:icons: font
:page-partial:
:source-highlighter: highlightjs

ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

include::{partialsdir}/README.adoc[tag=metadata]

== Objectiu

Aquest document constitueix un document de suport per al xref:tech-practices:ROOT:aim-and-scope.adoc[Codi de Pràctiques Tecnològiques] que implementa de manera pràctica el concepte de la *sobirania tecnològica*, expandint els principis que guien la nova direcció de l'Institut Municipal d'xref:glossary:ROOT:glossary.adoc#imi[Informàtica de Barcelona (IMI)] en matèria de tecnologia i innovació: interoperabilitat, agilitat, reutilització, ètica i obertura de coneixements i tecnologies.

Aquest document pretén contribuir a que IMI posi en pràctica la línia estratègica de l'Ajuntament de Barcelona que consisteix a incorporar *les tecnologies obertes i el programari* *lliure* en la major part dels seus serveis i processos tecnològics. 
Aquest principi de sobirania tecnològica, juntament amb la *metodologia àgil de desenvolupament de serveis i la gestió responsable de dades*, compon la visió a mitjà termini per a la transformació digital àgil pública a la ciutat de Barcelona.

Segons la declaració de París per al Open Government Partnership:

[quote, Paris Declaration for Open Government Partnership; en línia a https://paris-declaration.ogpsummit.org/topic/5820e48c2fd812b46ab9facc]
____
El programari de codi obert contribueix a fomentar la transparència i la col·laboració. 
El programari lliure és al cor de la innovació digital i tècnica. 
És el mitjà principal per prestar serveis digitals d'alta qualitat.
Els socis que s'hi uneixin buscaran promoure la transparència i la rendició de comptes del codi font obert i dels algoritmes que desenvolupin i utilitzin, sempre que sigui possible i apropiat. 
Els socis que s'hi uneixin miraran de dissenyar els serveis i implementar-los de manera no discriminatòria i treballar per maximitzar els beneficis de compartir i reutilitzar el codi governamental.
____

Un objectiu important d'aquest document, per tant, és ajudar els participants i interessats dels serveis digitals de l'Ajuntament de Barcelona a treballar amb tecnologies, solucions i projectes lliures; entendre quins són els drets i obligacions que es deriven de les llicències lliures; incentivar el desenvolupament, l'adquisició, l'ús i l'alliberament de programari; assegurar que els seus beneficis siguin aprofitats, i eliminar reticències que puguin existir per desconeixement dels seus diferents aspectes tècnics, organitzatius i jurídics.

== Àmbit d'aplicació

Aquest document serà aplicat en la gestió i la governança dels nous projectes de serveis digitals que entrin dins del Pla de transformació digital de l'Ajuntament de Barcelona.
